project_id = "bodyritual"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "bodyritual://auth/callback"
additional_redirect_urls = ["exp://127.0.0.1:8081/--/auth/callback", "bodyritual://auth/callback"]
jwt_expiry = 3600
enable_anonymous_sign_ins = true

[edge_runtime]
enabled = true
policy = "per_worker"
